export enum HomeActionTypes {
  HOME_ENTER = '[HOME PAGE] HOME_ENTER',
  FETCH_HEROES = '[HOME PAGE] FETCH_HEROES',
  FETCH_HEROES_SUCCESS = '[HOME PAGE] FETCH_HEROES_SUCCESS',
  FETCH_HEROES_FAILURE = '[HOME PAGE] FETCH_HEROES_FAILURE',
}
